# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntur" , primary: true do |ubuntur|
  
  ubuntur.vm.box = "ubuntu/bionic64"
  ubuntur.vm.box_version = "20180508.0.0"
  
  ubuntur.vm.hostname = "ubuntur"
  
  #make sure vagrant plugin install vagrant-disksize
  ubuntur.disksize.size = '50GB' 
  
  #make sure vagrant plugin install vagrant-vbguest
  ubuntur.vbguest.auto_update = true
  
  #Not using shared folder this atm -> it downloads what it needs
  #ubuntur.vm.synced_folder "./software", "/software", :mount_options => ["dmode=777","fmode=777"]

  #The Kafka Docker Swarm file uses this IP by default. In order to se the script as is, set this IP
  #for this to work make sure you use 
  ubuntur.vm.network :private_network, ip: "192.168.99.100"
  
  #vagrant plugin install vagrant-disksize
  #ubuntur.disksize.size = '30GB'
  
  ubuntur.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm"     , :id, "--memory", "4096"]
      vb.customize ["modifyvm"     , :id, "--name"  , "Ubuntu R"]
      vb.customize ["modifyvm"     , :id, "--cpus"  , 2]
	  vb.customize ["modifyvm"     , :id, "--clipboard","bidirectional"]
	  vb.customize ["modifyvm"     , :id, "--vram","16"]
  end
	
  #this starts provisioning the machine
  ubuntur.vm.provision :shell, path: "provision.sh"
  end

end
