# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'Installing vagrant-disksize Plugin...'
  system('vagrant plugin install vagrant-disksize')
end

unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "soamaster" , primary: true do |soamaster|
  soamaster.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  soamaster.vm.box = "ol7-latest"
  soamaster.vm.hostname = "soatest"
  soamaster.disksize.size = '75GB'
  soamaster.vbguest.auto_update = true
   
  #update this folder. it should contain oracle-xe-11.2.0-1.0.x86_64.rpm.zip and xe.rsp
  soamaster.vm.synced_folder "./software", "/software", :mount_options => ["dmode=777","fmode=777"]

  soamaster.vm.network :private_network, ip: "192.168.3.2"

  soamaster.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm"     , :id, "--memory", "8192"]
      vb.customize ["modifyvm"     , :id, "--name"  , "soatest"]
      vb.customize ["modifyvm"     , :id, "--cpus"  , 2]
	  vb.customize ["modifyvm"     , :id, "--clipboard","bidirectional"]
	  vb.customize ["modifyvm"     , :id, "--vram","16"]
  end
  #this makes sure the vagrant user and group have uid=1001 and guid=1001 so user oracle group oracle can have 1000
  soamaster.vm.provision :shell, path: "prepvagrantuser.sh"
  soamaster.vm.provision :reload
  soamaster.vm.provision :shell, path: "doneprepvagrantuser.sh"
  #this starts provisioning the machine
  soamaster.vm.provision :shell, path: "provision.sh"

  end

end
